// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ioc

import (
	"github.com/KNICEX/InkFlow/internal/action"
	"github.com/KNICEX/InkFlow/internal/ai"
	"github.com/KNICEX/InkFlow/internal/bff"
	"github.com/KNICEX/InkFlow/internal/code"
	"github.com/KNICEX/InkFlow/internal/comment"
	"github.com/KNICEX/InkFlow/internal/email"
	"github.com/KNICEX/InkFlow/internal/feed"
	"github.com/KNICEX/InkFlow/internal/ink"
	"github.com/KNICEX/InkFlow/internal/interactive"
	"github.com/KNICEX/InkFlow/internal/notification"
	"github.com/KNICEX/InkFlow/internal/recommend"
	"github.com/KNICEX/InkFlow/internal/relation"
	"github.com/KNICEX/InkFlow/internal/review"
	"github.com/KNICEX/InkFlow/internal/search"
	"github.com/KNICEX/InkFlow/internal/user"
	"github.com/KNICEX/InkFlow/internal/workflow/inkpub"
	"github.com/KNICEX/InkFlow/internal/workflow/schedule"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() *App {
	logger := InitLogger()
	db := InitDB(logger)
	universalClient := InitRedisUniversalClient()
	cmdable := InitRedisCmdable(universalClient)
	client := InitKafka()
	syncProducer := InitSyncProducer(client)
	v := user.InitUserService(db, cmdable, syncProducer, logger)
	v2 := email.InitService(logger)
	v3 := code.InitEmailCodeService(cmdable, v2)
	v4 := ink.InitInkService(cmdable, db, logger)
	v5 := interactive.InitInteractiveService(cmdable, syncProducer, db, logger)
	v6 := ink.InitRankingService(cmdable, db, logger, v5)
	v7 := relation.InitFollowService(cmdable, db, syncProducer, logger)
	v8 := comment.InitCommentService(db, cmdable, v4, syncProducer, logger)
	v9 := notification.InitNotificationService(db)
	gorsexClient := InitGorseCli()
	v10 := recommend.InitService(gorsexClient, v7, v5, logger)
	v11 := action.InitService()
	v12 := feed.InitService(db, v7, v11, logger)
	serviceManager := InitMeiliSearch()
	v13 := search.InitSearchService(serviceManager)
	clientClient := InitTemporalClient()
	handler := InitJwtHandler(cmdable)
	authentication := InitAuthMiddleware(handler, logger)
	v14 := bff.InitBff(v, v3, v4, v6, v7, v5, v8, v9, v10, v12, v13, clientClient, handler, authentication, logger)
	engine := InitGin(v14, logger)
	v15 := interactive.InitInteractiveInkReadConsumer(client, logger)
	v16 := InitGeminiClient()
	v17 := ai.InitLLMServices(v16)
	v18 := ai.InitLLMService(v17)
	v19 := review.InitService(v18)
	v20 := review.InitFailoverService(clientClient, v19, db, logger)
	v21 := review.InitReviewConsumer(clientClient, client, v19, v20, logger)
	v22 := search.InitSyncService(serviceManager)
	v23 := search.InitSyncConsumer(v22, client, logger)
	v24 := notification.InitNotificationConsumer(client, v9, v4, v8, logger)
	syncService := recommend.InitSyncService(gorsexClient)
	v25 := recommend.InitSyncConsumer(client, syncService, logger)
	v26 := InitConsumers(v15, v21, v23, v24, v25)
	v27 := review.InitAsyncService(syncProducer, logger)
	activities := inkpub.NewActivities(v4, v5, v27, v22, syncService, v9, v12)
	inkPubWorker := InitInkPubWorker(clientClient, activities)
	rankActivities := schedule.NewRankActivities(v6)
	rankTagWorker := InitRankTagWorker(clientClient, rankActivities)
	rankInkWorker := InitRankInkWorker(clientClient, rankActivities)
	reviewFailoverActivity := schedule.NewReviewFailoverActivity(v20)
	retryReviewWorker := InitRetryReviewWorker(clientClient, reviewFailoverActivity)
	v28 := InitWorkers(inkPubWorker, rankTagWorker, rankInkWorker, retryReviewWorker)
	rankInkScheduler := InitRankInkScheduler(clientClient)
	rankTagScheduler := InitRankTagScheduler(clientClient)
	reviewFailRetryScheduler := InitReviewRetryScheduler(clientClient)
	v29 := InitSchedulers(rankInkScheduler, rankTagScheduler, reviewFailRetryScheduler)
	app := &App{
		Server:     engine,
		Consumers:  v26,
		Workers:    v28,
		Schedulers: v29,
	}
	return app
}

// wire.go:

var thirdPartSet = wire.NewSet(
	InitLogger,
	InitDB,
	InitMeiliSearch,
	InitKafka,
	InitSyncProducer,
	InitRedisUniversalClient,
	InitRedisCmdable,
	InitGeminiClient,
	InitTemporalClient,
	InitGorseCli,
)

var webSet = wire.NewSet(
	InitJwtHandler,
	InitAuthMiddleware,
)
